name: bindworks_test_app
description: Bindworks test app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6

  #https://pub.dev/packages/flutter_mobx/
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #https://pub.dev/packages/provider
  provider: 6.0.5

  #https://pub.dev/packages/intl
  intl: ^0.18.1

  #https://pub.dev/packages/localstore
  localstore: 1.3.5

  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.1

  #https://pub.dev/packages/hive
  hive: ^2.2.3

  #https://pub.dev/packages/hive_flutter
  hive_flutter: ^1.1.0

  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.0.0

  #vychazi s flutter_secure_storage, jakorat je obohacena o biometricke udaje
  #https://pub.dev/packages/biometric_storage
  biometric_storage: 5.0.0

  #https://pub.dev/packages/local_auth
  local_auth: ^2.1.7

  #https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^4.0.2

  #https://pub.dev/packages/flutter_keyboard_visibility/
  flutter_keyboard_visibility: ^5.4.1

  #https://pub.dev/packages/fluentui_system_icons
  fluentui_system_icons: ^1.1.211

  #https://pub.dev/packages/device_info_plus
  device_info_plus: ^9.0.3

  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^4.1.0

  #https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.2

  # Routing
  #https://pub.dev/packages/go_router
  go_router: ^10.1.2

  #TODO nepouzivat uz 2 roky nikdo nespravuje radeji napsat vlastni
  password_strength: ^0.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/localization/en.json
    - assets/localization/cs.json

  fonts:
    - family: Biennale
      fonts:
        - asset: assets/fonts/Latinotype - Biennale Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/Latinotype - Biennale SemiBold.otf
          weight: 600
        - asset: assets/fonts/Latinotype - Biennale Bold.otf
          weight: 700
        - asset: assets/fonts/Latinotype - Biennale Bold.otf
          weight: 800

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/bindworks.png
  color_dark: "#121212"
  image_dark: assets/images/bindworks.png
  android_12:
    image: assets/images/bindworks.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/bindworks.png
    icon_background_color_dark: "#121212"
  web: false

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
